### ISSUE TITLE
use Generics

### ISSUE THREAD

**Issue by digitalkaoz** [phramz/dimple#8]
like 

```go
container.Get[TimeService](TimeService)
```

so we can skip manual casting afterwards

**Comment by phramz** [comment]
thanks @digitalkaoz ! I guess I'd need to sacrifice the `Container`-interface to use generics. Unfortunately that would be a huge trade off in terms of testing/mocking ... not so much within the library itself but for some implementations (e.g passing around `Container` to different packages for configuration or decoration of the `Container`). Right now I'm not sure wether its worth it or not. 

Maybe you have an idea how we could to keep the interface and still have the convenience of generics. WDT?
